data_dir: /projects/tenomix/ml-share/training/07/data
model_size: s
num_classes: 1
batch_size: 16
epochs: 100
learning_rate: 0.0007846285500668195
weight_decay: 0.004666993031173841
num_workers: 8
use_pu_loss: false
device: cuda
early_stopping_patience: 20
early_stopping_min_delta: 0.001
label_smooth: 0.1480608988200256
slice_stride: 5
mosaic_prob: 0.2312461052714101
use_clahe: false
use_shift_scale_rotate: true
use_brightness_contrast: false
_optuna_trial_number: 40
_optuna_ap50: 0.543022
