data_dir: /projects/tenomix/ml-share/training/07/data
model_size: s
num_classes: 1
batch_size: 32
epochs: 100
learning_rate: 0.0006399181555605165
weight_decay: 0.00019417018099651201
num_workers: 8
use_pu_loss: false
device: cuda
early_stopping_patience: 20
early_stopping_min_delta: 0.001
label_smooth: 0.08408016583070885
slice_stride: 5
mosaic_prob: 0.39188352450086295
use_clahe: false
use_shift_scale_rotate: true
use_brightness_contrast: false
_optuna_trial_number: 45
_optuna_ap50: 0.537361
