data_dir: /projects/tenomix/ml-share/training/07/data
model_size: s
num_classes: 1
batch_size: 16
epochs: 100
learning_rate: 0.00031541151070089215
weight_decay: 0.005267085623387704
num_workers: 8
use_pu_loss: false
device: cuda
early_stopping_patience: 20
early_stopping_min_delta: 0.001
label_smooth: 0.08866135543143575
slice_stride: 5
mosaic_prob: 0.3718090905629398
use_clahe: false
use_shift_scale_rotate: true
use_brightness_contrast: false
_optuna_trial_number: 98
_optuna_ap50: 0.557808
